// Config plugin: two Android Quick Settings tiles (Yellow Card / Red Card) that
// open bookem://yellow|red — the Android lock-screen-reachable path (pull the
// shade down over the keyguard). Tiles are the right surface here: Android caps an
// app at 2 tiles, which maps exactly to our two cards.
//
// android/ is a gitignored, prebuild-generated folder, so everything here is
// (re)written on each `expo prebuild`: the two TileService subclasses + a shared
// base, a monochrome tile icon, and the <service> manifest entries.
//
// A tile tap on a *secured* locked device calls unlockAndRun {} — the user gets
// the keyguard prompt first, then the card opens. We deliberately do NOT mark
// MainActivity showWhenLocked (that would change every launch); after unlock the
// normal launch shows the card.

const { withAndroidManifest, withDangerousMod, AndroidConfig } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const PACKAGE = "com.ghanbak.bookem";
const ICON_RES = "@drawable/ic_card_tile";
const QS_TILE_ACTION = "android.service.quicksettings.action.QS_TILE";

const TILES = [
  { className: "YellowCardTileService", uri: "bookem://yellow", label: "Yellow Card" },
  { className: "RedCardTileService", uri: "bookem://red", label: "Red Card" },
];

const BASE_KOTLIN = `package ${PACKAGE}

import android.app.PendingIntent
import android.content.Intent
import android.net.Uri
import android.os.Build
import android.service.quicksettings.TileService

// Shared Quick Settings tile behaviour. Each subclass supplies the card deep link.
// Generated by plugins/withQuickSettingsTiles.js — edits here are overwritten on
// the next \`expo prebuild\`.
abstract class CardTileService : TileService() {
    abstract val cardUri: String

    override fun onClick() {
        super.onClick()
        val intent = Intent(Intent.ACTION_VIEW, Uri.parse(cardUri)).apply {
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        val pendingIntent = PendingIntent.getActivity(
            this,
            0,
            intent,
            PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT,
        )
        // On a secure, currently-locked device, prompt unlock first, then open.
        if (isLocked) {
            unlockAndRun { startCard(pendingIntent, intent) }
        } else {
            startCard(pendingIntent, intent)
        }
    }

    private fun startCard(pendingIntent: PendingIntent, intent: Intent) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
            // Intent overload is deprecated on API 34+.
            startActivityAndCollapse(pendingIntent)
        } else {
            @Suppress("DEPRECATION")
            startActivityAndCollapse(intent)
        }
    }
}
`;

const subclassKotlin = (t) => `package ${PACKAGE}

// Generated by plugins/withQuickSettingsTiles.js — do not edit.
class ${t.className} : CardTileService() {
    override val cardUri = "${t.uri}"
}
`;

// Monochrome rounded-rectangle "card" glyph; the system tints it for the tile.
const TILE_DRAWABLE = `<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path
        android:fillColor="#FFFFFFFF"
        android:pathData="M8,2 L16,2 C17.66,2 19,3.34 19,5 L19,19 C19,20.66 17.66,22 16,22 L8,22 C6.34,22 5,20.66 5,19 L5,5 C5,3.34 6.34,2 8,2 Z" />
</vector>
`;

function withTileManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.service = app.service ?? [];
    for (const t of TILES) {
      const name = `.${t.className}`;
      if (app.service.some((s) => s.$?.["android:name"] === name)) continue;
      app.service.push({
        $: {
          "android:name": name,
          "android:exported": "true",
          "android:icon": ICON_RES,
          "android:label": t.label,
          "android:permission": "android.permission.BIND_QUICK_SETTINGS_TILE",
        },
        "intent-filter": [
          { action: [{ $: { "android:name": QS_TILE_ACTION } }] },
        ],
      });
    }
    return cfg;
  });
}

function withTileSources(config) {
  return withDangerousMod(config, [
    "android",
    (cfg) => {
      const root = cfg.modRequest.platformProjectRoot;
      const pkgDir = path.join(root, "app/src/main/java", ...PACKAGE.split("."));
      fs.mkdirSync(pkgDir, { recursive: true });
      fs.writeFileSync(path.join(pkgDir, "CardTileService.kt"), BASE_KOTLIN);
      for (const t of TILES) {
        fs.writeFileSync(path.join(pkgDir, `${t.className}.kt`), subclassKotlin(t));
      }
      const drawableDir = path.join(root, "app/src/main/res/drawable");
      fs.mkdirSync(drawableDir, { recursive: true });
      fs.writeFileSync(path.join(drawableDir, "ic_card_tile.xml"), TILE_DRAWABLE);
      return cfg;
    },
  ]);
}

module.exports = (config) => withTileSources(withTileManifest(config));
